---
# Set up nginx server

# Rename default default.conf
- name: stat default.conf
  stat: path=/etc/nginx/conf.d/default.conf
  register: default_conf
- name: rename default.conf
  command: mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf_
  # This works because the nginx import command is
  # `include /etc/nginx/conf.d/*.conf;`
  when: default_conf.stat.exists

# Ansible uses python. Python uses pip to install modules
# This means pip should be installed.
- name: Install pip
  apt:
    name: python-pip
    state: present

# htpasswd ansible module requires passlib
- name: Install latest passlib with pip
  pip: name=passlib

# set htpasswd credentials for account serviceuser
# edit the password in vars/crashdump.yml.example
# to set nginx_crashdump_password
- name: set account credentials in htpasswd
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: serviceuser
    password: "{{ nginx_crashdump_password }}"
    owner: root
    group: root
    mode: 0644

# configure nginx virtual host for proxy
# NOTE: ../templates/ is used 
#   by roles/nginx/tasks/proxy_cache.yml
#   for fileglob import
- name: copy conf.d
  template:
    src: "{{item}}"
    dest: /etc/nginx/conf.d/
    mode: 0644
    owner: root
    group: root
  become: yes
  with_fileglob:
    - ../templates_crashdump/*

# restart nginx
- name: nginx restart
  become: yes
  service:
    name: nginx
    enabled: yes
    state: restarted

